# Generated by Django 2.1.7 on 2019-08-14 17:51

import bnboats_app.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fab_year', models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2030)])),
                ('title', models.CharField(max_length=40)),
                ('manufacturer', models.CharField(max_length=30)),
                ('size', models.IntegerField(default=0)),
                ('capacity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('overnight_capacity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('bathrooms', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('rooms', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('animals', models.CharField(default='0', max_length=30)),
                ('smoke', models.CharField(default='0', max_length=30)),
                ('wheelchair', models.CharField(default='0', max_length=30)),
                ('has_discount', models.CharField(default='0', max_length=30)),
                ('postcode', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('additional', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('price_overnight', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('price_day', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('price_half_day', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('price_single', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('fish_rules', models.CharField(blank=True, max_length=30, null=True)),
                ('fish_bait', models.CharField(blank=True, max_length=30, null=True)),
                ('fish_places', models.CharField(blank=True, max_length=30, null=True)),
                ('review_score', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('reviews_count', models.IntegerField(default=0)),
                ('log', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('InReview', 'InReview'), ('Published', 'Published'), ('Paused', 'Paused'), ('Deleted', 'Deleted')], default=('InReview', 'InReview'), max_length=30)),
                ('keywords', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('owner_price_overnight', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('owner_price_day', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('owner_price_half_day', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('owner_price_single', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='BoatAmenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid_ba', models.CharField(default='ZZZ', max_length=3, unique=True)),
                ('type', models.CharField(choices=[('EL', 'EL'), ('CO', 'CO'), ('AA', 'AA'), ('LA', 'LA'), ('EQ', 'EQ')], default=('EL', 'EL'), max_length=2)),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'BoatAmenities',
            },
        ),
        migrations.CreateModel(
            name='BoatFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bnboats_app.Boat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BoatFishingSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid_bfs', models.CharField(default='ZZZ', max_length=3, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BoatImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boat_image', models.ImageField(null=True, upload_to=bnboats_app.models.get_member_upload_to, verbose_name='Image')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BoatPriceIncludes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid_bpi', models.CharField(default='ZZZ', max_length=3, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BoatType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid_bt', models.CharField(default='ZZZ', max_length=3, unique=True)),
                ('name', models.CharField(default='Boat Type blank', max_length=25)),
                ('image', models.ImageField(null=True, upload_to=bnboats_app.models.get_member_upload_to, verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('no_passengers', models.IntegerField(default=1)),
                ('booking_period', models.CharField(default='08', max_length=20)),
                ('status', models.CharField(choices=[('New', 'New'), ('PaymentPending', 'PaymentPending'), ('Paid', 'Paid'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default=('New', 'New'), max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('boat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bnboats_app.Boat')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaptainExtraActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid_cea', models.CharField(default='ZZZ', max_length=3, unique=True)),
                ('activity', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CaptainLanguages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid_cl', models.CharField(default='ZZZ', max_length=3, unique=True)),
                ('language', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CaptainProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_captaion', models.CharField(blank=True, max_length=30, null=True)),
                ('license_type', models.CharField(blank=True, max_length=30, null=True)),
                ('lt_professional', models.CharField(blank=True, max_length=60, null=True)),
                ('experience', models.CharField(blank=True, max_length=30, null=True)),
                ('extra_activities', models.ManyToManyField(to='bnboats_app.CaptainExtraActivities')),
                ('languages', models.ManyToManyField(to='bnboats_app.CaptainLanguages')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=25)),
                ('nearby_cities', models.ManyToManyField(blank=True, related_name='_city_nearby_cities_+', to='bnboats_app.City')),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='IBGECityCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ibge_id', models.IntegerField(default=0)),
                ('name', models.CharField(default='cidade', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_code', models.CharField(max_length=200)),
                ('payment_method', models.CharField(choices=[('Boleto', 'Boleto'), ('CCard', 'CCard'), ('DCard', 'DCard')], default=('Boleto', 'Boleto'), max_length=25)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_api_status', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_ccard_brand', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_ccard_no', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_total', models.CharField(blank=True, max_length=200, null=True)),
                ('paid_on_date', models.DateField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bnboats_app.Booking')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('sent_on', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('msg_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('msg_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=1000)),
                ('score', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Published', 'Published'), ('Hidden', 'Hidden'), ('Rejected', 'Rejected')], default=('New', 'New'), max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('country', models.CharField(default='Brasil', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=bnboats_app.models.get_member_upload_to, verbose_name='Image')),
                ('mobile_country', models.CharField(default='+55', max_length=3)),
                ('mobile_area', models.IntegerField(blank=True, null=True)),
                ('mobile_number', models.IntegerField(blank=True, null=True)),
                ('address_street', models.CharField(blank=True, max_length=60, null=True)),
                ('address_number', models.IntegerField(blank=True, null=True)),
                ('address_additional', models.CharField(blank=True, max_length=30, null=True)),
                ('address_postcode', models.CharField(blank=True, max_length=30, null=True)),
                ('address_area', models.CharField(blank=True, max_length=30, null=True)),
                ('address_city', models.CharField(blank=True, max_length=30, null=True)),
                ('address_state', models.CharField(blank=True, max_length=30, null=True)),
                ('address_country', models.CharField(default='Brasil', max_length=30)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default=('M', 'Male'), max_length=15)),
                ('dob_day', models.IntegerField(blank=True, null=True)),
                ('dob_month', models.CharField(blank=True, max_length=15, null=True)),
                ('dob_year', models.IntegerField(blank=True, null=True)),
                ('doc_type', models.CharField(choices=[('CPF', 'CPF'), ('Passport', 'Passport')], default=('CPF', 'CPF'), max_length=20)),
                ('doc_number', models.CharField(blank=True, max_length=14, null=True)),
                ('profile_desc', models.TextField(blank=True, max_length=500, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bnboats_app.UserProfile'),
        ),
        migrations.AddField(
            model_name='review',
            name='boat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bnboats_app.Boat'),
        ),
        migrations.AddField(
            model_name='review',
            name='notowner_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='bnboats_app.UserProfile'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bnboats_app.State'),
        ),
        migrations.AddField(
            model_name='boat',
            name='boat_amenities',
            field=models.ManyToManyField(blank=True, to='bnboats_app.BoatAmenities'),
        ),
        migrations.AddField(
            model_name='boat',
            name='boat_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bnboats_app.BoatType', to_field='sid_bt'),
        ),
        migrations.AddField(
            model_name='boat',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bnboats_app.City'),
        ),
        migrations.AddField(
            model_name='boat',
            name='fish_species',
            field=models.ManyToManyField(blank=True, to='bnboats_app.BoatFishingSpecies'),
        ),
        migrations.AddField(
            model_name='boat',
            name='images',
            field=models.ManyToManyField(to='bnboats_app.BoatImages'),
        ),
        migrations.AddField(
            model_name='boat',
            name='p_day_includes',
            field=models.ManyToManyField(blank=True, related_name='pd_includes', to='bnboats_app.BoatPriceIncludes'),
        ),
        migrations.AddField(
            model_name='boat',
            name='p_hday_includes',
            field=models.ManyToManyField(blank=True, related_name='phd_includes', to='bnboats_app.BoatPriceIncludes'),
        ),
        migrations.AddField(
            model_name='boat',
            name='p_overnight_includes',
            field=models.ManyToManyField(blank=True, related_name='po_includes', to='bnboats_app.BoatPriceIncludes'),
        ),
        migrations.AddField(
            model_name='boat',
            name='p_single_includes',
            field=models.ManyToManyField(blank=True, related_name='ps_includes', to='bnboats_app.BoatPriceIncludes'),
        ),
        migrations.AddField(
            model_name='boat',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
