# Generated by Django 2.1.7 on 2019-08-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnboats_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mobile_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
