# Generated by Django 2.1.7 on 2019-09-13 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnboats_app', '0005_auto_20190904_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='fab_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2030)]),
        ),
        migrations.AlterField(
            model_name='boat',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
