# Generated by Django 2.1.7 on 2019-09-18 21:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnboats_app', '0006_auto_20190913_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='capacity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)]),
        ),
    ]
