# Generated by Django 2.1.7 on 2019-09-20 07:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnboats_app', '0007_auto_20190918_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='boat',
            field=models.ForeignKey(null=True, on_delete=models.SET(251), to='bnboats_app.Boat'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=models.SET(251), related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
