# Generated by Django 2.1.7 on 2019-09-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnboats_app', '0008_auto_20190920_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fishing_client',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
