# Generated by Django 2.1.7 on 2019-10-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnboats_app', '0009_userprofile_fishing_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fishing_discount',
            field=models.BooleanField(default=False),
        ),
    ]
