# Generated by Django 2.1.7 on 2019-10-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnboats_app', '0011_auto_20191005_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='doc_number',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='doc_type',
            field=models.CharField(choices=[('CPF', 'CPF'), ('Passport', 'Passport'), ('CNPJ', 'CNPJ')], default=('CPF', 'CPF'), max_length=20),
        ),
    ]
