# Generated by Django 2.1.7 on 2019-10-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnboats_app', '0012_auto_20191009_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='boat_amenities',
            field=models.ManyToManyField(blank=True, related_name='boatamen', to='bnboats_app.BoatAmenities'),
        ),
    ]
