# Generated by Django 2.1.7 on 2019-10-22 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bnboats_app', '0013_auto_20191016_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='boat',
            name='main_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_image', to='bnboats_app.BoatImages'),
        ),
        migrations.AlterField(
            model_name='captainprofile',
            name='extra_activities',
            field=models.ManyToManyField(blank=True, to='bnboats_app.CaptainExtraActivities'),
        ),
        migrations.AlterField(
            model_name='captainprofile',
            name='languages',
            field=models.ManyToManyField(blank=True, to='bnboats_app.CaptainLanguages'),
        ),
    ]
