# Generated by Django 2.1.7 on 2019-10-23 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bnboats_app', '0014_auto_20191022_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boat',
            name='main_image',
        ),
    ]
