# Generated by Django 2.1.7 on 2019-11-05 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bnboats_app', '0015_remove_boat_main_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoatBlockedDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_dates', models.CharField(blank=True, max_length=5000, null=True)),
                ('boat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bnboats_app.Boat')),
            ],
        ),
        migrations.AlterField(
            model_name='boatfavorite',
            name='boat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bnboats_app.Boat'),
        ),
    ]
